- hosts: grupo1
  become: yes
  become_method: sudo
  tasks:
  - name: ensure Java Runtime Environment is installed
    yum:
      name: jdk
      state: present
  - name: create directory for Calculator
    file:
      path: /var/calculator
      state: directory
  - name: configure Calculator as a service
    file:
      path: /etc/init.d/calculadora2
      state: link
      force: yes
      src: /var/calculator/calculadora2.jar
  - name: copy Calculator
    copy:
      src: build/libs/calculadora-0.0.1-SNAPSHOT.jar
      dest: /var/calculator/calculadora2.jar
      mode: a+x
    notify:
    - restart Calculator
  handlers:
  - name: restart Calculator
    service:
      name: calculadora2
      enabled: yes
      state: restarted
